import time
import smtplib

import streamlit as st
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from google import genai
from prompts import SYSTEM_PROMPT


# -----------------------------
# Page configuration
# -----------------------------

st.set_page_config(
    page_title="MechSnap AI",
    page_icon="🔧"
)


# -----------------------------
# Gemini API
# -----------------------------

GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]

client = genai.Client(
    api_key=GEMINI_API_KEY
)

# Models are tried in this order. If the first one is overloaded
# (or not found), the app automatically moves to the next one.
MODEL_NAMES = [
    "gemini-3.8-flash",
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
]


# -----------------------------
# Session memory
# -----------------------------

if "messages" not in st.session_state:
    st.session_state.messages = []

if "last_explanation" not in st.session_state:
    st.session_state.last_explanation = ""


# -----------------------------
# Gemini request with retry
# + model fallback
# -----------------------------

def generate_response(contents, retries_per_model=3):

    for model_name in MODEL_NAMES:

        for attempt in range(retries_per_model):

            try:

                response = client.models.generate_content(
                    model=model_name,
                    contents=contents
                )

                return response.text or (
                    "⚠️ Gemini returned an empty response. "
                    "Please try again."
                )

            except Exception as error:

                error_text = str(error)

                # Model does not exist
                if (
                    "404" in error_text
                    or "NOT_FOUND" in error_text
                ):
                    break

                # Temporary server / rate-limit problems
                if (
                    "503" in error_text
                    or "UNAVAILABLE" in error_text
                    or "500" in error_text
                    or "429" in error_text
                ):

                    if attempt < retries_per_model - 1:

                        time.sleep(2 ** attempt)

                    continue

                # Other errors
                return (
                    "❌ Something went wrong while contacting Gemini.\n\n"
                    f"Error: {error}"
                )

    return (
        "⚠️ Gemini is temporarily busy right now.\n\n"
        "Please wait a minute and try again."
    )


# -----------------------------
# Send explanation by email
# -----------------------------

def send_email(receiver_email, subject, explanation):

    sender_email = st.secrets["EMAIL_ADDRESS"]
    sender_password = st.secrets["EMAIL_PASSWORD"]

    message = MIMEMultipart()

    message["From"] = sender_email
    message["To"] = receiver_email
    message["Subject"] = subject

    email_body = f"""
MechSnap AI
Your AI Mechanical Engineering Study Assistant
================================================

{explanation}

================================================
Generated by MechSnap AI
"""

    message.attach(
        MIMEText(email_body, "plain")
    )

    try:

        with smtplib.SMTP(
            "smtp.gmail.com",
            587
        ) as server:

            server.starttls()

            server.login(
                sender_email,
                sender_password
            )

            server.send_message(message)

        return True, "Email sent successfully."

    except Exception as error:

        return False, str(error)


# -----------------------------
# Header
# -----------------------------

st.title("🔧 MechSnap AI")

st.write(
    "Your AI mechanical engineering study assistant."
)

st.caption(
    "📸 Snap • 🤖 Analyze • 📚 Learn • 📧 Share"
)

st.divider()


# -----------------------------
# Display previous messages
# -----------------------------

for message in st.session_state.messages:

    with st.chat_message(message["role"]):

        if message["type"] == "text":

            st.write(message["content"])

        elif message["type"] == "image":

            st.image(message["content"])


# -----------------------------
# Image upload
# -----------------------------

st.header("📸 Upload a question or diagram")

uploaded_file = st.file_uploader(
    "Upload an image",
    type=["jpg", "jpeg", "png"]
)


# -----------------------------
# Analyze image
# -----------------------------

if uploaded_file:

    image_bytes = uploaded_file.getvalue()

    st.image(
        image_bytes,
        caption="Uploaded image"
    )

    if st.button(
        "🤖 Explain with AI",
        type="primary"
    ):

        # Save image to conversation
        st.session_state.messages.append(
            {
                "role": "user",
                "type": "image",
                "content": image_bytes
            }
        )

        with st.spinner(
            "🔍 Analyzing your engineering image..."
        ):

            contents = [
                {
                    "text": SYSTEM_PROMPT
                },
                {
                    "inline_data": {
                        "mime_type": uploaded_file.type,
                        "data": image_bytes
                    }
                }
            ]

            answer = generate_response(contents)

        # Save AI response
        st.session_state.messages.append(
            {
                "role": "assistant",
                "type": "text",
                "content": answer
            }
        )

        # Store latest explanation
        st.session_state.last_explanation = answer

        st.rerun()


# -----------------------------
# Email sharing
# -----------------------------

if st.session_state.last_explanation:

    st.divider()

    st.header("📧 Share Explanation")

    st.write(
        "Send the latest MechSnap AI explanation by email."
    )

    receiver_email = st.text_input(
        "Recipient email address",
        placeholder="example@gmail.com"
    )

    email_subject = st.text_input(
        "Email subject",
        value="MechSnap AI - Engineering Explanation"
    )

    if st.button("📧 Send Explanation"):

        if not receiver_email.strip():

            st.warning(
                "Please enter a recipient email address."
            )

        elif not st.session_state.last_explanation.strip():

            st.warning(
                "There is no explanation available to send."
            )

        else:

            with st.spinner("📨 Sending email..."):

                success, result = send_email(
                    receiver_email.strip(),
                    email_subject.strip(),
                    st.session_state.last_explanation
                )

            if success:

                st.success(
                    "✅ Explanation sent successfully!"
                )

            else:

                st.error(
                    f"❌ Email could not be sent.\n\n{result}"
                )


# -----------------------------
# Follow-up chat
# -----------------------------

st.divider()

st.subheader("💬 Ask MechSnap AI")

user_question = st.chat_input(
    "Ask a follow-up question..."
)


if user_question:

    # Save user question
    st.session_state.messages.append(
        {
            "role": "user",
            "type": "text",
            "content": user_question
        }
    )

    with st.spinner("🧠 Thinking..."):

        conversation = [
            {
                "text": SYSTEM_PROMPT
            }
        ]

        # Add previous text conversation
        for message in st.session_state.messages:

            if message["type"] == "text":

                conversation.append(
                    {
                        "text": message["content"]
                    }
                )

        answer = generate_response(
            conversation
        )

    # Save AI response
    st.session_state.messages.append(
        {
            "role": "assistant",
            "type": "text",
            "content": answer
        }
    )

    # Update latest explanation
    st.session_state.last_explanation = answer

    st.rerun()

